name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-local:
 
    runs-on: windows-latest
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
     
    - name: Restore NuGet Packages
      run: nuget restore Tiefsee4.sln
 
    - name: Build Solution and archive artifacts
      run: msbuild Tiefsee4.sln /t:Tiefsee /p:Configuration=Release /p:Platform="Any CPU" /p:DeleteExistingFiles=True

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Tiefsee4
        path: Tiefsee.zip